"""Marked Markdown blocks and the overview SVG for the estate atlas.

The atlas owns the architecture. This module projects it into marked blocks
inside a doc file and into an ``atlas-glance.svg`` file beside that doc, so
prose cannot drift from data.

Standard library only. Output is deterministic: no timestamps except the
traffic block's own "as of" date, which comes from its input file.
"""
from __future__ import annotations


import html
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .render import (
    _mmd_id,
    _write,
    order_cards,
    parse_atlas,
    read_json_file,
    render_mermaid,
)

TRAFFIC_SCHEMA = "estate-atlas-traffic@1"

GENERATED_LINE = "<!-- Generated by estate-atlas; edit the atlas, not this block -->"
BLOCK_NAMES = ("glance", "owners", "layers", "traffic")
BEGIN_RE = re.compile(r"<!--\s*atlas:begin\s+(\S+?)\s*-->")
END_RE = re.compile(r"<!--\s*atlas:end\s+(\S+?)\s*-->")
MARK_RE = re.compile(r"<!--\s*atlas:(begin|end)\s+(\S+?)\s*-->")
REFRESH_LINE = "Refresh: rebuild the traffic snapshot, then rewrite the doc blocks."
PLACEHOLDER_LINE = "No traffic snapshot yet."
WRITE_HINT = "rewrite the doc blocks"

GLANCE_IMAGE = "[![The estate at a glance](atlas-glance.svg)](atlas.html)"
GLANCE_SENTENCE = ("Generated from the atlas: solid parts run today, dashed ones are "
                   "planned or partial; open the atlas page for evidence and live state.")


def esc_cell(value: Any) -> str:
    """Markdown table cell text with pipes escaped."""
    return str(value).replace("\n", " ").replace("|", "\\|").strip()


def xml_esc(value: Any) -> str:
    return html.escape(str(value), quote=False)


def xml_attr(value: Any) -> str:
    return html.escape(str(value), quote=True)


# ---------------------------------------------------------------- blocks

def glance_block(atlas: dict[str, Any]) -> str:
    """At-a-glance block: image link, one sentence, mermaid details."""
    mermaid = render_mermaid(atlas, "flows").rstrip("\n")
    return "\n".join([
        GENERATED_LINE,
        "",
        GLANCE_IMAGE,
        "",
        GLANCE_SENTENCE,
        "",
        "<details><summary>The same diagram as text (mermaid)</summary>",
        "",
        "```mermaid",
        mermaid,
        "```",
        "",
        "</details>",
    ])


def owners_block(atlas: dict[str, Any]) -> str:
    """Who-owns-what table, one row per contract in atlas order."""
    titles = {c["id"]: c["title"] for c in atlas["components"]}
    lines = [GENERATED_LINE, "",
             "| Record | Only writer | Format | Readers |",
             "|---|---|---|---|"]
    for contract in atlas["contracts"]:
        title = esc_cell(contract["title"])
        if contract["status"] != "live":
            record = "**%s** (%s)" % (title, contract["status"])
        else:
            record = title
        producer = esc_cell(titles.get(contract["producer"], contract["producer"]))
        format_cell = esc_cell(contract["format"])
        readers = ", ".join(
            esc_cell(titles.get(cid, cid)) for cid in contract["consumers"])
        lines.append("| %s | %s | %s | %s |" % (record, producer, format_cell, readers))
    return "\n".join(lines)


def _evidence_count(comp: dict[str, Any]) -> int:
    total = len(comp.get("evidence", []))
    for surface in comp.get("surfaces", []):
        total += len(surface.get("evidence", []))
    return total


def layers_block(atlas: dict[str, Any]) -> str:
    """Per-layer appendix: heading, summary, component table."""
    ordered = order_cards(atlas)
    comp_by_id = {c["id"]: c for c in atlas["components"]}
    parts = [GENERATED_LINE]
    for index, layer in enumerate(atlas["layers"]):
        if index > 0:
            parts.append("")
        parts.append("#### " + layer["title"])
        parts.append("")
        parts.append(layer["summary"])
        parts.append("")
        parts.append("| Part | Status | Home | Evidence | Planned evidence |")
        parts.append("|---|---|---|---|---|")
        for cid in ordered.get(layer["id"], []):
            comp = comp_by_id[cid]
            expect = comp.get("expect", [])
            planned = str(len(expect)) if expect else "\u2013"
            parts.append("| %s | %s | %s | %d | %s |" % (
                esc_cell(comp["title"]), comp["status"],
                esc_cell(comp["home"]), _evidence_count(comp), planned))
    return "\n".join(parts)


# ---------------------------------------------------------------- traffic

def _count(value: Any) -> int:
    """A non-negative integer count from a traffic document, 0 for anything else."""
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value != value or value < 0:
        return 0
    return int(value)


def _pct(part: int, total: int) -> str:
    return "%d%%" % round(100 * part / total) if total > 0 else "0%"


def _as_of(generated: Any) -> str:
    if isinstance(generated, bool) or not isinstance(generated, (int, float)):
        return "an unknown time"
    stamp = datetime.fromtimestamp(float(generated), timezone.utc)
    return stamp.strftime("%Y-%m-%d %H:%M UTC")


def traffic_block(atlas: dict[str, Any], traffic_doc: dict[str, Any] | None) -> str:
    """The weekly traffic snapshot from an `estate-atlas-traffic@1` document; None gives the placeholder."""
    if traffic_doc is None:
        return "\n".join([GENERATED_LINE, "", PLACEHOLDER_LINE, "", REFRESH_LINE])
    if not isinstance(traffic_doc, dict) or traffic_doc.get("schema") != "estate-atlas-traffic@1":
        raise ValueError("--traffic is not an estate-atlas-traffic@1 document")
    titles = {c["id"]: c["title"] for c in atlas["components"]}
    ends = {f["id"]: (f["from"], f["to"]) for f in atlas["flows"]}
    cov = traffic_doc.get("coverage") if isinstance(traffic_doc.get("coverage"), dict) else {}
    total = _count(cov.get("records"))
    pulse_pct = _count(cov.get("pulse"))
    as_of = ("As of %s: %d records this week, %s declared" % (
        _as_of(traffic_doc.get("generated")), total, _pct(_count(cov.get("declared")), total)))
    if pulse_pct > 0:
        as_of += ", %s pulse" % (_pct(pulse_pct, total),)
    as_of += ", %s inferred, %s internal, %s unrouted." % (
        _pct(_count(cov.get("inferred")), total), _pct(_count(cov.get("internal")), total),
        _pct(_count(cov.get("unrouted")), total))
    lines = [GENERATED_LINE, "",
             as_of,
             "",
             "| Flow | From → To | This week | Last 24 h | Declared / inferred | Pulse |",
             "|---|---|---|---|---|---|"]
    flows = traffic_doc.get("flows") if isinstance(traffic_doc.get("flows"), dict) else {}
    rows = []
    for fid, entry in flows.items():
        if not isinstance(fid, str) or not isinstance(entry, dict):
            continue
        d7 = _count(entry.get("d7"))
        pulse_d7 = _count(entry.get("pulse_d7"))
        if d7 == 0 and pulse_d7 == 0:
            continue
        basis = entry.get("by_basis") if isinstance(entry.get("by_basis"), dict) else {}
        rows.append((d7 == 0, -d7, -pulse_d7, fid, _count(entry.get("d24")),
                     _count(basis.get("declared")), _count(basis.get("inferred")), pulse_d7))
    for _pulse_only, neg_d7, _neg_pulse, fid, d24, declared, inferred, pulse_d7 in sorted(rows)[:15]:
        frm, to = ends.get(fid, ("?", "?"))
        lines.append("| %s | %s → %s | %d | %d | %d / %d | %d |" % (
            esc_cell(fid), esc_cell(titles.get(frm, frm)), esc_cell(titles.get(to, to)), -neg_d7, d24,
            declared, inferred, pulse_d7))
    if not rows:
        lines.append("| (no flow carried a record) | | 0 | 0 | 0 / 0 | 0 |")
    cross = traffic_doc.get("crosschecks") if isinstance(traffic_doc.get("crosschecks"), dict) else {}
    silent = sorted(f for f in cross.get("silent") or [] if isinstance(f, str))
    lines += ["", "Silent live flows: " + (", ".join(esc_cell(f) for f in silent) if silent else "none"),
              "", REFRESH_LINE]
    return "\n".join(lines)


# ---------------------------------------------------------------- svg

SVG_TITLE = "The estate at a glance"
CARD_H = 40
BAND_PAD = 10
ARC_SPACE = 30
BAND_H = BAND_PAD + ARC_SPACE + CARD_H + 16
BAND_GAP = 16
MARGIN = 16
LABEL_W = 150
LABEL_GAP = 12
CARD_GAP = 12
SVG_STATUSES = ("live", "partial", "planned", "documented", "absent", "retired")

SVG_STYLE = (":root{--band:#f8fafc;--card:#ffffff;--line:#cbd5e1;--ink:#0f172a;"
             "--muted:#475569;--live:#166534;--partial:#92400e;--other:#475569;"
             "--edge-live:#15803d;--edge-partial:#b45309;--edge-other:#64748b;"
             "--edge-absent:#b91c1c}"
             "@media (prefers-color-scheme: dark){:root{--band:#111c33;--card:#16223d;"
             "--line:#3b4d6b;--ink:#f1f5f9;--muted:#cbd5e1;--live:#4ade80;"
             "--partial:#fbbf24;--other:#cbd5e1;--edge-live:#4ade80;"
             "--edge-partial:#fbbf24;--edge-other:#94a3b8;--edge-absent:#f87171}}"
             ".band{fill:var(--band);stroke:var(--line)}"
             ".band-title{fill:var(--ink);font-size:13px;font-weight:600}"
             ".card{stroke-width:2}"
             ".card-live{fill:var(--card);stroke:var(--live)}"
             ".card-partial{fill:var(--card);stroke:var(--partial);stroke-dasharray:6 4}"
             ".card-planned,.card-documented,.card-absent,.card-retired{fill:var(--card);"
             "stroke:var(--other);stroke-dasharray:6 4;opacity:.55}"
             ".card-title{fill:var(--ink);font-size:12px;font-weight:600}"
             ".card-home{fill:var(--muted);font-size:10px}"
             ".flow{fill:none;stroke-width:1.8}"
             ".flow-live{stroke:var(--edge-live)}"
             ".flow-partial{stroke:var(--edge-partial)}"
             ".flow-planned,.flow-documented{stroke:var(--edge-other);"
             "stroke-dasharray:6 4;opacity:.6}"
             ".flow-absent,.flow-retired{stroke:var(--edge-absent);"
             "stroke-dasharray:6 4;opacity:.6}"
             "text{font-family:system-ui,sans-serif}")


def _card_width(title: str) -> int:
    return max(110, min(220, len(title) * 7 + 24))


def _int(value: float) -> int:
    return int(round(float(value)))


def glance_svg(atlas: dict[str, Any]) -> str:
    """Static glance SVG: one band per layer, cards in order_cards order."""
    ordered = order_cards(atlas)
    comp_by_id = {c["id"]: c for c in atlas["components"]}
    widths = {c["id"]: _card_width(c["title"]) for c in atlas["components"]}
    layers = list(atlas["layers"])

    def row_width(lid: str) -> int:
        ids = ordered.get(lid, [])
        if not ids:
            return 0
        return sum(widths[cid] for cid in ids) + CARD_GAP * (len(ids) - 1)

    content = max([LABEL_W + LABEL_GAP + row_width(layer["id"]) for layer in layers] or [0])
    width = MARGIN * 2 + BAND_PAD * 2 + content
    height = MARGIN * 2 + len(layers) * BAND_H + max(0, len(layers) - 1) * BAND_GAP

    pos: dict[str, dict[str, int]] = {}
    for index, layer in enumerate(layers):
        band_y = MARGIN + index * (BAND_H + BAND_GAP)
        cursor = MARGIN + BAND_PAD + LABEL_W + LABEL_GAP
        card_y = band_y + BAND_PAD + ARC_SPACE
        for cid in ordered.get(layer["id"], []):
            w = widths[cid]
            pos[cid] = {"x": cursor, "y": card_y, "w": w, "h": CARD_H,
                        "band": band_y}
            cursor += w + CARD_GAP

    parts = ['<svg xmlns="http://www.w3.org/2000/svg" role="img" width="%d" '
             'height="%d" viewBox="0 0 %d %d">' % (width, height, width, height),
             "<title>" + xml_esc(SVG_TITLE) + "</title>",
             "<style>" + SVG_STYLE + "</style>",
             "<defs>" + "".join(
                 '<marker id="arr-%s" viewBox="0 0 10 10" refX="8" refY="5" '
                 'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
                 '<path d="M0,0 L10,5 L0,10 z" class="flow flow-%s" '
                 'style="stroke:none"/></marker>' % (s, s) for s in SVG_STATUSES)
             + "</defs>"]
    for index, layer in enumerate(layers):
        band_y = MARGIN + index * (BAND_H + BAND_GAP)
        band_w = width - MARGIN * 2
        parts.append('<rect class="band" x="%d" y="%d" width="%d" height="%d" rx="10"/>'
                     % (MARGIN, band_y, band_w, BAND_H))
        parts.append('<text class="band-title" x="%d" y="%d" dominant-baseline="central">%s</text>'
                     % (MARGIN + BAND_PAD, band_y + BAND_H // 2, xml_esc(layer["title"])))
    cards: list[str] = []  # drawn after the flows, so a card hides the lines that pass behind it
    for cid in [c["id"] for c in atlas["components"] if c["id"] in pos]:
        comp = comp_by_id[cid]
        box = pos[cid]
        status = comp["status"] if comp["status"] in SVG_STATUSES else "planned"
        node_id = _mmd_id("svg_" + cid)
        cards.append('<g id="%s"><rect class="card card-%s" x="%d" y="%d" '
                     'width="%d" height="%d" rx="8"/>'
                     % (xml_attr(node_id), status, box["x"], box["y"], box["w"], box["h"]))
        cx = box["x"] + box["w"] // 2
        cards.append('<text class="card-title" x="%d" y="%d" text-anchor="middle">%s</text>'
                     % (cx, box["y"] + 17, xml_esc(comp["title"])))
        cards.append('<text class="card-home" x="%d" y="%d" text-anchor="middle">%s</text>'
                     % (cx, box["y"] + 31, xml_esc(comp["home"])))
        cards.append("</g>")
    for flow in sorted(atlas["flows"], key=lambda f: f["id"]):
        src = pos.get(flow["from"])
        dst = pos.get(flow["to"])
        if src is None or dst is None:
            continue
        status = flow["status"] if flow["status"] in SVG_STATUSES else "planned"
        x1 = src["x"] + src["w"] // 2
        x2 = dst["x"] + dst["w"] // 2
        if comp_by_id[flow["from"]]["layer"] == comp_by_id[flow["to"]]["layer"]:
            top = min(src["y"], dst["y"])
            lift = max(24, abs(x2 - x1) // 4)
            y = top
            d = ("M%d,%d C%d,%d %d,%d %d,%d"
                 % (x1, y, x1, y - lift, x2, y - lift, x2, y))
        else:
            y1 = src["y"] + src["h"]
            y2 = dst["y"]
            bend = (y2 - y1) // 2
            d = ("M%d,%d C%d,%d %d,%d %d,%d"
                 % (x1, y1, x1, y1 + bend, x2, y2 - bend, x2, y2))
        label = flow["contract"] if flow.get("contract") else flow["id"]
        parts.append('<path class="flow flow-%s" d="%s" marker-end="url(#arr-%s)">'
                     "<title>%s</title></path>"
                     % (status, xml_attr(d), status, xml_esc(label)))
    parts.extend(cards)
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------- markers

def parse_blocks(text: str) -> dict[str, str]:
    """Map block name to its raw inner text; raises ValueError on bad markers."""
    matches = list(MARK_RE.finditer(text))
    inners: dict[str, str] = {}
    seen: set[str] = set()
    index = 0
    while index < len(matches):
        kind, name = matches[index].group(1), matches[index].group(2)
        if kind != "begin":
            raise ValueError("stray atlas:end marker for %r without begin" % (name,))
        if name in seen:
            raise ValueError("duplicated atlas:begin marker for %r" % (name,))
        seen.add(name)
        if index + 1 >= len(matches):
            raise ValueError("missing atlas:end marker for %r" % (name,))
        kind2, name2 = matches[index + 1].group(1), matches[index + 1].group(2)
        if kind2 != "end":
            raise ValueError("missing atlas:end marker for %r" % (name,))
        if name2 != name:
            raise ValueError("atlas marker mismatch: begin %r closed by end %r"
                             % (name, name2))
        inners[name] = text[matches[index].end():matches[index + 1].start()]
        index += 2
    return inners


def replace_blocks(text: str, blocks: dict[str, str]) -> str:
    """Replace the inside of each named block; raises ValueError on bad markers."""
    matches = list(MARK_RE.finditer(text))
    seen: set[str] = set()
    order: list[tuple[str, Any, Any]] = []
    index = 0
    while index < len(matches):
        kind, name = matches[index].group(1), matches[index].group(2)
        if kind != "begin":
            raise ValueError("stray atlas:end marker for %r without begin" % (name,))
        if name in seen:
            raise ValueError("duplicated atlas:begin marker for %r" % (name,))
        seen.add(name)
        if index + 1 >= len(matches):
            raise ValueError("missing atlas:end marker for %r" % (name,))
        kind2, name2 = matches[index + 1].group(1), matches[index + 1].group(2)
        if kind2 != "end":
            raise ValueError("missing atlas:end marker for %r" % (name,))
        if name2 != name:
            raise ValueError("atlas marker mismatch: begin %r closed by end %r"
                             % (name, name2))
        order.append((name, matches[index], matches[index + 1]))
        index += 2
    for name in blocks:
        if name not in seen:
            raise ValueError("missing atlas block %r" % (name,))
    out: list[str] = []
    cursor = 0
    for name, begin, end in order:
        out.append(text[cursor:begin.start()])
        out.append(text[begin.start():begin.end()])
        out.append("\n")
        if name in blocks:
            out.append(blocks[name].strip("\n"))
        else:
            out.append(text[begin.end():end.start()].strip("\n"))
        out.append("\n")
        out.append(text[end.start():end.end()])
        cursor = end.end()
    out.append(text[cursor:])
    return "".join(out)


def _traffic_inner_empty(inner: str) -> bool:
    rest = [line for line in inner.splitlines()
            if line.strip() and line.strip() != GENERATED_LINE]
    return not rest


def load_atlas(path: Path) -> dict[str, Any]:
    return parse_atlas(read_json_file(path))


def svg_path_for(doc_path: Path) -> Path:
    return doc_path.parent / "atlas-glance.svg"


# ---------------------------------------------------------------- commands

def write(atlas_path: Path, doc_path: Path,
          traffic_path: Path | None = None,
          svg_path: Path | None = None) -> tuple[int, str]:
    """Rewrite the marked blocks in the doc and the glance SVG.

    The SVG defaults to ``atlas-glance.svg`` beside the doc. Returns an exit
    code (0, 1 or 2) and a message.
    """
    atlas_path = Path(atlas_path)
    doc_path = Path(doc_path)
    if traffic_path is not None:
        traffic_path = Path(traffic_path)
    if svg_path is None:
        svg_path = svg_path_for(doc_path)
    else:
        svg_path = Path(svg_path)
    try:
        atlas = load_atlas(atlas_path)
    except Exception as exc:
        return 2, "cannot load atlas: %s" % (exc,)
    try:
        text = doc_path.read_text(encoding="utf-8")
    except OSError as exc:
        return 2, "cannot read doc: %s" % (exc,)
    try:
        current = parse_blocks(text)
    except ValueError as exc:
        return 2, "%s" % (exc,)
    blocks = {
        "glance": glance_block(atlas),
        "owners": owners_block(atlas),
        "layers": layers_block(atlas),
    }
    if traffic_path is not None:
        try:
            traffic_doc = read_json_file(traffic_path)
        except Exception as exc:
            return 2, "cannot load traffic: %s" % (exc,)
        if not isinstance(traffic_doc, dict):
            return 2, "traffic file must hold a JSON object"
        try:
            blocks["traffic"] = traffic_block(atlas, traffic_doc)
        except ValueError as exc:
            return 2, "%s" % (exc,)
    elif "traffic" in current and _traffic_inner_empty(current["traffic"]):
        blocks["traffic"] = traffic_block(atlas, None)
    try:
        updated = replace_blocks(text, blocks)
    except ValueError as exc:
        return 2, "%s" % (exc,)
    try:
        _write(doc_path, updated if updated.endswith("\n") else updated + "\n")
        _write(svg_path, glance_svg(atlas))
    except OSError as exc:
        return 2, "cannot write output: %s" % (exc,)
    return 0, "ok"


def _traffic_ok(inner: str) -> bool:
    if GENERATED_LINE not in inner:
        return False
    if PLACEHOLDER_LINE in inner:
        return True
    return "As of " in inner


def check_docs(atlas_path: Path, doc_path: Path,
               svg_path: Path | None = None) -> tuple[int, str]:
    """Check the doc blocks and the glance SVG against the atlas.

    The SVG defaults to ``atlas-glance.svg`` beside the doc. Returns an exit
    code (0, 1 or 2) and a message.
    """
    atlas_path = Path(atlas_path)
    doc_path = Path(doc_path)
    if svg_path is None:
        svg_path = svg_path_for(doc_path)
    else:
        svg_path = Path(svg_path)
    try:
        atlas = load_atlas(atlas_path)
    except Exception as exc:
        return 2, "cannot load atlas: %s" % (exc,)
    try:
        text = doc_path.read_text(encoding="utf-8")
    except OSError as exc:
        return 2, "cannot read doc: %s" % (exc,)
    try:
        current = parse_blocks(text)
    except ValueError as exc:
        return 2, "%s; %s" % (exc, WRITE_HINT)
    for name in ("glance", "owners", "layers", "traffic"):
        if name not in current:
            return 2, "missing atlas block %r; %s" % (name, WRITE_HINT)
    expected = {
        "glance": glance_block(atlas),
        "owners": owners_block(atlas),
        "layers": layers_block(atlas),
    }
    for name, fresh in expected.items():
        if current[name].strip("\n") != fresh.strip("\n"):
            return 1, "block %r is stale; %s" % (name, WRITE_HINT)
    if not _traffic_ok(current["traffic"]):
        return 1, "traffic block is missing its snapshot or placeholder; %s" % (WRITE_HINT,)
    try:
        # newline-normalised: a checkout that stores LF may hold the file as CRLF
        actual_svg = svg_path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    except (OSError, UnicodeDecodeError):
        return 1, "%s is missing; %s" % (svg_path.name, WRITE_HINT)
    if actual_svg != glance_svg(atlas):
        return 1, "%s is stale; %s" % (svg_path.name, WRITE_HINT)
    return 0, "ok"
