"""Plain-English explanations of the estate atlas, from facts only.

The atlas says what the parts are, what feeds them and what they feed. This
module turns those facts into short sentences and tour documents.

Standard library only. Output is deterministic: the same inputs give the same
bytes. Text is plain: no Markdown, no HTML. Numbers carry thousands
separators.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .render import _write, order_cards, parse_atlas, read_json_file

EXPLAIN_SCHEMA = "estate-atlas-explain@1"
EXPLAIN_ALL_SCHEMA = "estate-atlas-explain-all@1"
TOUR_SCHEMA = "estate-atlas-tour@1"
TRAFFIC_SCHEMA = "estate-atlas-traffic@1"

GENERATED_NOTE = "Generated by estate-atlas. Do not edit."
TOUR_WRITE_HINT = "rewrite the tour doc"

EMD = "\u2014"  # written as an escape: the validator bans the literal character
ELL = "\u2026"
HEART = "\u2665"
ARROW = "\u2192"

GAP_STATUSES = ("planned", "partial", "documented", "absent")
LINE_ORDER = ("what", "fed_by", "feeds", "contracts", "running",
              "this_week", "gaps")


def _count(value: Any) -> int:
    """A non-negative integer count, 0 for anything else."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return 0
    if value != value or value < 0:
        return 0
    return int(value)


def _fmt(value: Any) -> str:
    return format(_count(value), ",d")


def _join(items: list[str]) -> str:
    """Oxford-free join: a, b and c."""
    items = [item for item in items]
    if len(items) <= 1:
        return "".join(items)
    if len(items) == 2:
        return "%s and %s" % (items[0], items[1])
    return "%s and %s" % (", ".join(items[:-1]), items[-1])


def _as_of(generated: Any) -> str:
    if isinstance(generated, bool) or not isinstance(generated, (int, float)):
        return "an unknown time"
    stamp = datetime.fromtimestamp(float(generated), timezone.utc)
    return stamp.strftime("%Y-%m-%d %H:%M UTC")


def _traffic_entry(traffic: dict[str, Any] | None, fid: str) -> dict[str, Any]:
    if not isinstance(traffic, dict):
        return {}
    flows = traffic.get("flows")
    if not isinstance(flows, dict):
        return {}
    entry = flows.get(fid)
    return entry if isinstance(entry, dict) else {}


def _flow_volume(traffic: dict[str, Any] | None, fid: str) -> tuple[int, int, int, int]:
    """(d7, d24, pulse_d7, declared_d7) for one flow; missing entries are 0."""
    entry = _traffic_entry(traffic, fid)
    basis = entry.get("by_basis")
    if not isinstance(basis, dict):
        basis = {}
    return (_count(entry.get("d7")), _count(entry.get("d24")),
            _count(entry.get("pulse_d7")), _count(basis.get("declared")))


def _volume_suffix(flow: dict[str, Any], traffic: dict[str, Any] | None) -> str:
    if traffic is None:
        return ""
    d7, _d24, pulse, _declared = _flow_volume(traffic, str(flow.get("id", "")))
    if d7 > 0:
        return " %s %s crossings this week" % (EMD, _fmt(d7))
    if pulse > 0:
        return " %s %s %s heartbeats this week" % (EMD, HEART, _fmt(pulse))
    if flow.get("traffic"):
        return " %s nothing this week" % (EMD,)
    return ""


def _flow_key(traffic: dict[str, Any] | None, flow: dict[str, Any]) -> tuple[int, str]:
    fid = str(flow.get("id", ""))
    if traffic is None:
        return (0, fid)
    d7, _d24, pulse, _declared = _flow_volume(traffic, fid)
    return (-(d7 + pulse), fid)


def _touching(atlas: dict[str, Any], cid: str) -> list[dict[str, Any]]:
    return [f for f in atlas.get("flows", []) if isinstance(f, dict)
            and (f.get("from") == cid or f.get("to") == cid)]


def _off_status_ids(traffic: dict[str, Any]) -> list[str]:
    cross = traffic.get("crosschecks")
    if not isinstance(cross, dict):
        return []
    raw = cross.get("off_status") or []
    if not isinstance(raw, list):
        return []
    out: list[str] = []
    for item in raw:
        if isinstance(item, str):
            out.append(item)
        elif isinstance(item, dict):
            fid = item.get("flow", item.get("id"))
            if isinstance(fid, str):
                out.append(fid)
    return out


def _silent_ids(traffic: dict[str, Any]) -> list[str]:
    cross = traffic.get("crosschecks")
    if not isinstance(cross, dict):
        return []
    raw = cross.get("silent") or []
    if not isinstance(raw, list):
        return []
    return [item for item in raw if isinstance(item, str)]


# ---------------------------------------------------------------- explain


def explain(atlas: dict[str, Any], component_id: str,
            traffic: dict[str, Any] | None = None,
            live: dict[str, Any] | None = None) -> dict[str, Any]:
    """One plain-English `estate-atlas-explain@1` document for a component."""
    comps = {c["id"]: c for c in atlas.get("components", [])
             if isinstance(c, dict) and isinstance(c.get("id"), str)}
    if component_id not in comps:
        raise KeyError(component_id)
    comp = comps[component_id]
    titles = {c["id"]: str(c.get("title", c["id"])) for c in comps.values()}
    layers = {layer["id"]: layer for layer in atlas.get("layers", [])
              if isinstance(layer, dict) and isinstance(layer.get("id"), str)}
    layer = layers.get(str(comp.get("layer")), {})

    lines: list[dict[str, Any]] = []

    # what: always present.
    title = str(comp.get("title", component_id))
    home = str(comp.get("home", "?"))
    status = str(comp.get("status", "?"))
    summary = str(comp.get("summary", ""))
    what = "%s (%s) is %s. %s" % (title, home, status, summary)
    expect = [e for e in comp.get("expect") or [] if isinstance(e, dict) and e.get("path")]
    if status != "live" and expect:
        what += " It is expected in %s." % (_join(["%s %s" % (e.get("repo", "?"), e["path"]) for e in expect[:3]]),)
    owns = comp.get("owns") or []
    if isinstance(owns, list) and [o for o in owns if isinstance(o, str)]:
        what += " It owns %s." % (_join([str(o) for o in owns if isinstance(o, str)]),)
    lines.append({"kind": "what", "text": what, "refs": []})

    in_flows = sorted(
        (f for f in atlas.get("flows", [])
         if isinstance(f, dict) and f.get("to") == component_id),
        key=lambda f: _flow_key(traffic, f))
    out_flows = sorted(
        (f for f in atlas.get("flows", [])
         if isinstance(f, dict) and f.get("from") == component_id),
        key=lambda f: _flow_key(traffic, f))

    def flow_sentences(flows: list[dict[str, Any]], verb: str,
                       other_end: str) -> tuple[str, list[str]]:
        shown = flows[:6]
        parts: list[str] = []
        refs: list[str] = []
        for flow in shown:
            fid = str(flow.get("id", ""))
            other = str(flow.get(other_end, ""))
            parts.append("%s %s (%s)%s." % (
                verb, titles.get(other, other),
                str(flow.get("trigger", "")), _volume_suffix(flow, traffic)))
            refs.append("component:" + other)
            refs.append("flow:" + fid)
        text = " ".join(parts)
        if len(flows) > 6:
            text += " %s and %s more." % (ELL, _fmt(len(flows) - 6))
        return text, refs

    if in_flows:
        text, refs = flow_sentences(in_flows, "Fed by", "from")
        lines.append({"kind": "fed_by", "text": text, "refs": refs})
    if out_flows:
        text, refs = flow_sentences(out_flows, "Feeds", "to")
        lines.append({"kind": "feeds", "text": text, "refs": refs})

    contracts = [c for c in atlas.get("contracts", []) if isinstance(c, dict)]
    writes = [c for c in contracts if c.get("producer") == component_id]
    reads = [c for c in contracts
             if isinstance(c.get("consumers"), list) and component_id in c["consumers"]]
    if writes or reads:
        parts = []
        refs = []
        if writes:
            parts.append("It writes %s." % (
                _join([str(c.get("title", c.get("id"))) for c in writes]),))
            refs.extend("contract:" + str(c.get("id")) for c in writes)
        if reads:
            parts.append("It reads %s." % (
                _join([str(c.get("title", c.get("id"))) for c in reads]),))
            refs.extend("contract:" + str(c.get("id")) for c in reads)
        lines.append({"kind": "contracts", "text": " ".join(parts), "refs": refs})

    entry = live.get(component_id) if isinstance(live, dict) else None
    if isinstance(entry, dict):
        by_status = entry.get("by_status")
        if not isinstance(by_status, dict):
            by_status = {}
        ordered = sorted(by_status.items(),
                         key=lambda kv: (0 if kv[0] == "live" else 1, str(kv[0])))
        running = "Running now: %s instances" % (_fmt(entry.get("instances")),)
        if ordered:
            running += " (%s)" % (", ".join(
                "%s %s" % (_fmt(count), name) for name, count in ordered),)
        failing = entry.get("failing") or []
        if isinstance(failing, list) and failing:
            shown = failing[:3]
            nouns = []
            for item in shown:
                if isinstance(item, dict):
                    nouns.append("%s on %s" % (
                        item.get("intent", "?"), item.get("subject", "?")))
            noun = "failing condition" if len(failing) == 1 else "failing conditions"
            running += "; %s %s: %s" % (_fmt(len(failing)), noun, ", ".join(nouns))
        lines.append({"kind": "running", "text": running, "refs": []})

    if traffic is not None:
        touching = _touching(atlas, component_id)
        total_d7 = total_d24 = total_pulse = 0
        for flow in touching:
            d7, d24, pulse, _declared = _flow_volume(traffic, str(flow.get("id", "")))
            total_d7 += d7
            total_d24 += d24
            total_pulse += pulse
        week = ("This week: %s records crossed its flows "
                "(%s in the last 24 hours)." % (_fmt(total_d7), _fmt(total_d24)))
        if total_pulse > 0:
            week += " It keeps a heartbeat of %s pulses." % (_fmt(total_pulse),)
        flow_by_id = {str(f.get("id")): f for f in touching}
        refs = []
        touched = set(flow_by_id)
        for fid in sorted(set(_silent_ids(traffic)) & touched):
            week += " %s is silent." % (fid,)
            refs.append("flow:" + fid)
        carried = {str(o.get("flow")): _count(o.get("d7"))
                   for o in ((traffic or {}).get("crosschecks") or {}).get("off_status") or []
                   if isinstance(o, dict)}
        for fid in sorted(set(_off_status_ids(traffic)) & touched):
            if carried.get(fid, 0) <= 0:
                continue
            week += " %s carried %s records while marked %s." % (
                fid, _fmt(carried[fid]), flow_by_id[fid].get("status", "?"))
            refs.append("flow:" + fid)
        lines.append({"kind": "this_week", "text": week, "refs": refs})

    gaps = sorted(
        (f for f in _touching(atlas, component_id)
         if f.get("status") in GAP_STATUSES),
        key=lambda f: str(f.get("id", "")))
    if gaps:
        lines.append({
            "kind": "gaps",
            "text": " ".join("%s is %s: %s" % (
                f.get("id"), f.get("status"), f.get("gap") or "") for f in gaps),
            "refs": ["flow:" + str(f.get("id")) for f in gaps],
        })

    order = {kind: i for i, kind in enumerate(LINE_ORDER)}
    lines.sort(key=lambda line: order.get(line["kind"], len(order)))
    union = sorted({ref for line in lines for ref in line["refs"]})
    return {
        "schema": EXPLAIN_SCHEMA,
        "id": component_id,
        "title": title,
        "layer": str(comp.get("layer", "")),
        "layer_title": str(layer.get("title", "")),
        "status": status,
        "home": home,
        "lines": lines,
        "refs": union,
    }


# ---------------------------------------------------------------- tour


def _busy(traffic: dict[str, Any], atlas: dict[str, Any], cid: str) -> int:
    total = 0
    for flow in _touching(atlas, cid):
        d7, _d24, _pulse, _declared = _flow_volume(traffic, str(flow.get("id", "")))
        total += d7
    return total


def tour(atlas: dict[str, Any],
         traffic: dict[str, Any] | None = None) -> dict[str, Any]:
    """A `estate-atlas-tour@1` walk: each layer with its busiest parts, then flows."""
    comps = [c for c in atlas.get("components", [])
             if isinstance(c, dict) and isinstance(c.get("id"), str)]
    comp_by_id = {c["id"]: c for c in comps}
    ordered = order_cards(atlas)
    steps: list[dict[str, Any]] = []
    for layer in atlas.get("layers", []):
        if not isinstance(layer, dict):
            continue
        lid = str(layer.get("id", ""))
        steps.append({"kind": "layer", "id": lid,
                      "title": str(layer.get("title", lid)),
                      "text": str(layer.get("summary", ""))})
        members = [c["id"] for c in comps if c.get("layer") == lid]
        if traffic is not None:
            picked = sorted(members,
                            key=lambda cid: (-_busy(traffic, atlas, cid), cid))[:3]
        else:
            picked = list(ordered.get(lid, members))[:3]
        for cid in picked:
            part = explain(atlas, cid, traffic=traffic)
            texts = {line["kind"]: line["text"] for line in part["lines"]}
            text = texts.get("what", "")
            if "this_week" in texts:
                text += " " + texts["this_week"]
            steps.append({"kind": "part", "id": cid,
                          "title": str(comp_by_id[cid].get("title", cid)),
                          "text": text})
    if traffic is not None:
        titles = {c["id"]: str(c.get("title", c["id"])) for c in comps}
        ranked = sorted(
            (f for f in atlas.get("flows", []) if isinstance(f, dict)),
            key=lambda f: (-_flow_volume(traffic, str(f.get("id", "")))[3],
                           str(f.get("id", ""))))[:5]
        for flow in ranked:
            frm = str(flow.get("from", ""))
            to = str(flow.get("to", ""))
            declared = _flow_volume(traffic, str(flow.get("id", "")))[3]
            steps.append({
                "kind": "flow",
                "id": str(flow.get("id", "")),
                "title": "%s %s %s" % (titles.get(frm, frm), ARROW, titles.get(to, to)),
                "text": "%s %s %s: %s. %s declared crossings this week." % (
                    titles.get(frm, frm), ARROW, titles.get(to, to),
                    str(flow.get("trigger", "")), _fmt(declared)),
            })
    return {"schema": TOUR_SCHEMA, "steps": steps}


# ---------------------------------------------------------------- markdown


def _esc(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("<", "&lt;")


def render_tour_md(atlas: dict[str, Any],
                   traffic: dict[str, Any] | None = None,
                   *, note: str = GENERATED_NOTE) -> str:
    """The tour as Markdown; ``note`` is the provenance line an embedding project may set."""
    if not isinstance(note, str) or not note.strip() or "\n" in note or "\r" in note:
        raise ValueError("note must be one non-empty line")
    doc = tour(atlas, traffic)
    lines = ["# A tour of the estate", "", note, ""]
    if traffic is not None:
        generated = traffic.get("generated") if isinstance(traffic, dict) else None
        lines += ["As of %s" % (_as_of(generated),), ""]
    for step in doc["steps"]:
        if step["kind"] == "layer":
            lines += ["## " + _esc(step["title"]), "", _esc(step["text"]), ""]
        elif step["kind"] == "part":
            lines += ["### " + _esc(step["title"]), "", _esc(step["text"]), ""]
    lines += ["## Busiest flows", ""]
    flows = [step for step in doc["steps"] if step["kind"] == "flow"]
    if flows:
        for step in flows:
            lines += ["### " + _esc(step["title"]), "", _esc(step["text"]), ""]
    else:
        lines += ["No traffic snapshot yet.", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------- commands


def _load_atlas(path: Path) -> dict[str, Any]:
    return parse_atlas(read_json_file(path))


def _load_traffic(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    doc = read_json_file(path)
    if not isinstance(doc, dict) or doc.get("schema") != TRAFFIC_SCHEMA:
        raise ValueError("--traffic is not an %s document" % (TRAFFIC_SCHEMA,))
    return doc


def _load_live(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    doc = read_json_file(path)
    if isinstance(doc, dict) and isinstance(doc.get("live"), dict) and "schema" in doc:
        return doc["live"]
    if isinstance(doc, dict):
        return doc
    raise ValueError("--live must hold a JSON object")


def _dump(obj: dict[str, Any]) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def do_part(atlas_path: Path, component_id: str,
            traffic_path: Path | None, live_path: Path | None) -> int:
    try:
        atlas = _load_atlas(atlas_path)
        traffic = _load_traffic(traffic_path)
        live = _load_live(live_path)
    except Exception as exc:
        print("atlas_explain: cannot load input: %s" % (exc,), file=sys.stderr)
        return 2
    try:
        doc = explain(atlas, component_id, traffic=traffic, live=live)
    except KeyError:
        print("atlas_explain: unknown component %r" % (component_id,), file=sys.stderr)
        return 2
    sys.stdout.write(_dump(doc))
    return 0


def do_all(atlas_path: Path, traffic_path: Path | None, live_path: Path | None) -> int:
    try:
        atlas = _load_atlas(atlas_path)
        traffic = _load_traffic(traffic_path)
        live = _load_live(live_path)
    except Exception as exc:
        print("atlas_explain: cannot load input: %s" % (exc,), file=sys.stderr)
        return 2
    parts = {c["id"]: explain(atlas, c["id"], traffic=traffic, live=live)
             for c in atlas["components"]}
    sys.stdout.write(_dump({"schema": EXPLAIN_ALL_SCHEMA,
                            "parts": parts, "tour": tour(atlas, traffic)}))
    return 0


def do_tour_md(atlas_path: Path, traffic_path: Path | None,
               write: Path | None) -> int:
    try:
        atlas = _load_atlas(atlas_path)
        traffic = _load_traffic(traffic_path)
    except Exception as exc:
        print("atlas_explain: cannot load input: %s" % (exc,), file=sys.stderr)
        return 2
    text = render_tour_md(atlas, traffic)
    if not text.endswith("\n"):
        text += "\n"
    if write is None:
        sys.stdout.write(text)
        return 0
    try:
        _write(write, text)
    except OSError as exc:
        print("atlas_explain: cannot write output: %s" % (exc,), file=sys.stderr)
        return 2
    return 0


def check_tour(doc_path: Path, atlas: dict[str, Any],
               *, note: str = GENERATED_NOTE,
               write_hint: str = TOUR_WRITE_HINT) -> tuple[bool, str]:
    """Check the tour doc against the atlas without traffic.

    ``note`` and ``write_hint`` are the embedding project's provenance line
    and refresh hint; the defaults are estate-atlas's own.

    Returns ``(ok, message)``: ``True`` when the doc matches what
    :func:`render_tour_md` would write, ``False`` with a reason otherwise.
    """
    doc_path = Path(doc_path)
    if not isinstance(write_hint, str) or not write_hint.strip() or "\n" in write_hint or "\r" in write_hint:
        return False, "write_hint must be one non-empty line"
    try:
        actual = doc_path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    except (OSError, UnicodeDecodeError) as exc:
        return False, "cannot read doc: %s" % (exc,)
    try:
        expected = render_tour_md(atlas, None, note=note)
    except ValueError as exc:
        return False, str(exc)
    if not expected.endswith("\n"):
        expected += "\n"
    if actual == expected:
        return True, "ok"
    return False, "%s is stale; %s" % (doc_path.name, write_hint)
